image: elixir:1.7

variables:
  MIX_ENV: test
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - deps
    - _build

stages:
  - test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile --force

lint:
  stage: test
  script:
    - mix format --check-formatted

unit-testing:
  stage: test
  coverage: '/(\d+\.\d+\%) \| Total/'
  script:
    - mix test --trace --seed 0 --preload-modules --cover
